### ISSUE TITLE
all zero values for PV-Storage-Parameters

### ISSUE THREAD

**Issue by nailend** [windnode/WindNODE_ABW#100]
all values are zero in results_scns[scenario]['parameters']['Installierte Kapazität PV-Batteriespeicher'] for either 'NEP2035' as well as ISE2050_Relimit

**Comment by nesnoj** [comment]
Thanks for this observation!
Yepp, that's in line with what you put into our scenario table - only BAThigh and BATlimit scenarios contain PV storage systems.
I'll close this one and move the discussion on the agenda for tomorrow.

**Comment by nesnoj** [comment]
Result: We went for this scenario configuration as the NEP assumes own-consumption for PV storage systems so subsequently they cannot be used as regional/grid flex. In the BAThigh+BATlimit scns we assume that there are additional capacities for the ladder.
