### ISSUE TITLE
extract max load/nominal power of heat storage 

### ISSUE THREAD

**Issue by nailend** [windnode/WindNODE_ABW#106]
Heat storage:

Capacity already exists in : `results_scns[scenario]['parameters']['Installed capacity heat storage']`

max load/nominal power per AGS needs to be extracted from cfg.

Thank you

**Comment by nesnoj** [comment]
Hmm..actually, the data in the DF you mention contains the power not the storage capacity!
It's all about the term "capacity" again :(
I'll have a deeper look here...
