### ISSUE TITLE
additional/missing multiindex entry depending on scenario

### ISSUE THREAD

**Issue by nailend** [windnode/WindNODE_ABW#108]
The multiindex of the DF of battery storages consists of `level` and `ags`. Depending on the scenarios, there are `level=large` or `level=large,small` (PV-Storage-scenarios)
This difference will most probably lead to errors while executing papermill as I call these levels directly.

What's is the best way to deal with this?
- try, except
- if-loop
- generate zero-value DFs if `small` is not in multindex

`results_scns[scenario]['results_axlxt']['Batteriespeicher nach Gemeinde']['discharge']`

**Comment by nesnoj** [comment]
I see 2 options:
1. skip calc for small bats and hide the left subplot using if.. 
2. use 0 values for small and add a markdown note just before the plot that all values for small bats are 0 if not installed.

I'd prefer 1 but if 2 is faster to implement, go for it.

**Comment by nesnoj** [comment]
Hey @nailend, I had a similar situation with the abs. areas for gmPV+wind in SQ scenario and used the following approach:
2d72d18668146ae98a81856d756af64ff2a1f486

**Comment by nailend** [comment]
> Hey @nailend, I had a similar situation with the abs. areas for gmPV+wind in SQ scenario and used the following approach:
> 
> 2d72d18668146ae98a81856d756af64ff2a1f486

Thx. Had to solve it with zero values for now.
