### ISSUE TITLE
Wrong calc of th. storage use

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#110]
The calculation of th storage cycles & use in the template in `feature/#99-flexi-plots` needs to be fixed.
(@nailend on your question: you calculated cap/power and hence you'll get the c rate which is constant -> the discharge energy+power were mixed up)
Also, the var `full_load_cycles` is misleading as it is rather a storage usage rate..

I'll prepare something..

PS: Furthermore, the script crashes in cell 28 (?) since `flex_ratios_heat` is not defined..

**Comment by nailend** [comment]
> The calculation of th storage cycles & use in the template in `feature/#99-flexi-plots` needs to be fixed.
> (@nailend on your question: you calculated cap/power and hence you'll get the c rate which is constant -> the discharge energy+power were mixed up)
Thanks! Reviewing your changes I was still wondering... The naming isn't quite intuitive because of eng/ger

> Also, the var `full_load_cycles` is misleading as it is rather a storage usage rate..
True. Storage usage rate sounds comprehensable.

> I'll prepare something..
Thanks!

> PS: Furthermore, the script crashes in cell 28 (?) since `flex_ratios_heat` is not defined..
Yes, I got stuck in #108 as I had to change some calculations after #107. Will fix this!
