### ISSUE TITLE
Relative use of dec. th. storages very low

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#112]
This is due to the high c-rate (6.7) of small storages which makes the rel. usage using eq. full cycles not very meaningful.

It might be good to drop the rel. values and use total cycles only as indicator @gplssm?

**Comment by nailend** [comment]
fixed by https://github.com/windnode/WindNODE_ABW/pull/116/commits/7506f4249b98eacd62a5f1395a239dd502ef0e65

**Comment by gplssm** [comment]
Is this really a bug? I doubt it. If not, we could close this issue with #116

**Comment by nesnoj** [comment]
Not really a bug, rather a proposal to use a different indicator. Close if it is changed in #116.
