### ISSUE TITLE
Battery-Storage-large (dis)charge is low in NEP2035

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#113]
Checking 1month NEP2035 with
```
results_scns['NEP2035']['results_axlxt']['Stromerzeugung nach Gemeinde'].sum(axis=1)/(
    results_scns['NEP2035']['results_axlxt']['Stromnachfrage nach Gemeinde'].sum(axis=1) + 
    results_scns['NEP2035']['results_axlxt']['Stromnachfrage Wärme nach Gemeinde'].sum(axis=1)
)
```
reveals, that 15091391 has got the most power production related to the demand, maybe the grid might be not able to handle this?!
I checked full year data for NEP2035 and no storage is used at all.

- I'd say it's cheaper to extend the grid but this needs to be analyzed in detail..
- Also, some 2050 scenarios should be checked.

**Comment by nailend** [comment]
@nesnoj  also with the 1month scenario there is only 1 charge and 1 discharge event. Strangely enough the model first discharges the storages and then charges it afterwards but with extra loses?!

![grafik](https://user-images.githubusercontent.com/51374526/88982285-26889980-d2c8-11ea-95c6-bc55859670e2.png)

**Comment by nesnoj** [comment]
I compared ISE2050_Relimit with 2 different costs for line invest:

**ISE2050_Relimit: normal costs**
`results_scns['ISE2050_Relimit']['parameters']['Newly installed capacity grid'].sum()` = 4.13
![bat2](https://user-images.githubusercontent.com/15910173/89038394-8fabf380-d340-11ea-9408-ca935624ad48.png)

**ISE2050_Relimit: normal costs x 100**
`results_scns['ISE2050_Relimit_expensive_line_invest']['parameters']['Newly installed capacity grid'].sum()` = 0
![bat1](https://user-images.githubusercontent.com/15910173/89038451-a9e5d180-d340-11ea-85e9-df2c922f9c1b.png)

Although the bats are used more extensively, the line invest seems to be quite low for the 1st one.

**Comment by gplssm** [comment]
I've tested some further cases to investigate the interdependency between grid and battery storage

As base, I used scenario ISE2050_PTHiselargestor
Note: ignore the zero-cycles of small batteries. In this scenario, capacity is zero.

| Variation | Varied parameter |
| --- | --- |
| normal | none |
| no-cost-large-storage | variable cost of large battery storages is set to zero |
| grid-cap-10-percent | Existing grid capacity per line scaled down to 10 % of the normal capacity. Grid investment remains untouched |
| grid-cap-0.1-percent | Existing grid capacity per line scaled down to 0.1 % of the normal capacity. Grid investment remains untouched |

## normal

![line_loading_ISE2050_PTHiselargestor_normal](https://user-images.githubusercontent.com/8255114/89295982-0f4c0200-d662-11ea-9418-3d76504cf1a2.png)

![bat_storage_ISE2050_PTHiselargestor_normal](https://user-images.githubusercontent.com/8255114/89295998-1410b600-d662-11ea-8c14-6474566e3e91.png)

## no-cost-large-storage

![line_loading_ISE2050_PTHiselargestor_no-cost-large-storage](https://user-images.githubusercontent.com/8255114/89296095-30145780-d662-11ea-9368-d9351b669825.png)
![bat_storage_ISE2050_PTHiselargestor_no-cost-large-storage](https://user-images.githubusercontent.com/8255114/89296103-3276b180-d662-11ea-8040-fc25022a3208.png)

### grid-cap-10-percent

![line_loading_ISE2050_PTHiselargestor_grid-cap-10-percent](https://user-images.githubusercontent.com/8255114/89296173-44585480-d662-11ea-97c4-0493139a7fdc.png)
![bat_storage_ISE2050_PTHiselargestor_grid-cap-10-percent](https://user-images.githubusercontent.com/8255114/89296178-46221800-d662-11ea-9e22-8612527fa061.png)

## grid-cap-0.1-percent

![line_loading_ISE2050_PTHiselargestor_grid-cap-0 1-percent](https://user-images.githubusercontent.com/8255114/89296410-94371b80-d662-11ea-9766-92d651ddc523.png)
![bat_storage_ISE2050_PTHiselargestor_grid-cap-0 1-percent](https://user-images.githubusercontent.com/8255114/89296203-51754380-d662-11ea-8110-c140b5cf3f4a.png)

## Conclusions

* There is a strong dependency between grid and storages
* The grid seems to be oversized as in the normal scenario there is plenty of free capacity (as annual sum)
* I've checked the `.lp` file and saw that large scale battery storages have variable cost of 2 EUR/MWh assigned for charge **and** discharge. Grid does not have variable cost
* Even setting variable cost of bat. storages to zero, does not have much effect

### Next steps

* Would be interesting to see how bat. storages perform in annual simulation. Maybe different supply patterns in other seasons make batteries perform better
* We should take a look on imports (and exports) when looking at battery storage utilization. Maybe this is used as cheap flexibilization option

**Comment by gplssm** [comment]
I did full year simulation for three scenarios in order to see if battery utilization increases when a full year in analyzed

### ISE2050_Relimit

![newplot(1)](https://user-images.githubusercontent.com/8255114/89617694-fbcfaf80-d88a-11ea-985f-33585743fbcf.png)

### ISE2050_PTHisenostor

![Battery_utilization_ISE2050_PTHisenostor](https://user-images.githubusercontent.com/8255114/89617775-199d1480-d88b-11ea-9600-b08926266752.png)

### ISE2050_PTHiselargestor

![Battery_utilization_ISE2050_PTHiselargestor](https://user-images.githubusercontent.com/8255114/89617889-4cdfa380-d88b-11ea-966c-79e89a2b64af.png)

## Conclusions

- Slightly more battery utilization than in the monthly scenario, but still very low

## Next step

- Take a look on 2050 scenarios with limited electricity import in order to assess the interdependency between battery storage utilization and electricity imports

**Comment by gplssm** [comment]
Looking at scenario `ISE2050_AUT90_BAThigh` (annual simulation), doesn't change the picture that much

![newplot (1)](https://user-images.githubusercontent.com/8255114/89930855-a63d2f00-dc0b-11ea-8ba7-f7f7f41b1780.png)

- large-scale battery storage

**Comment by gplssm** [comment]
When we look at generation and demand for the entire region, it gets even more obvious (ISE2050_AUT90_BAThigh):
![newplot (3)](https://user-images.githubusercontent.com/8255114/90015522-02a25c00-dca9-11ea-9bdb-8605de4aeaa6.png)

Generation by wind **OR** PV would be sufficient to supply regions demand. Hence, costly flexibility options not being used that much seems to quite plausible.
I guess this is a general problem for all ISE2050 scenarios.

Let's take a look on NEP2035 scenario:
![newplot (4)](https://user-images.githubusercontent.com/8255114/90015762-5614aa00-dca9-11ea-99d0-f2c9bfa16469.png)

Not such a massive problem, but there are still almost 3 TWh of export out of 5,5 TWh total demand.

**Comment by gplssm** [comment]
After fixing [data handling issues](https://github.com/windnode/WindNODE_ABW/pull/142) number of total cycles for large-scale battery storages them much more plausible (NEP2035 full year)!

![newplot(2)](https://user-images.githubusercontent.com/8255114/90118179-25d81480-dd58-11ea-99d1-9ee4c82613e8.png)

I'll take a look on a scenario with small-scale batteries now. If it looks promising too, I gonna close this for now. We should still hae in mind the large scale exports which are assumed to decrease demand for flexibility dispatch.

**Comment by gplssm** [comment]
As already mentioned in https://github.com/windnode/WindNODE_ABW/issues/127#issuecomment-673392294 there is something wrong with the calculation of total cycles for small-scale batteries

![newplot (1)](https://user-images.githubusercontent.com/8255114/90123536-46579d00-dd5f-11ea-835c-767595b97d1e.png)

Once, this is clarified, we can assess discharge of small-scale storages again.

**Comment by gplssm** [comment]
Values seem much more plausible now! See also: https://github.com/windnode/WindNODE_ABW/issues/127#issuecomment-673550156

I would like to have a look new on the new scenario `NEP_RE-_BAT` and resulting battery utilization.

**Comment by gplssm** [comment]
I took the new scenario `NEP_RE-_BAT+` for investigating battery utilization with decreased RES installations.

With this new scenario batteries are used more. Max. with 10 % Utilization rate in Muldestausee.

![newplot](https://user-images.githubusercontent.com/8255114/90285388-18b04800-de74-11ea-8563-fe652d05caf8.png)

![newplot (3)](https://user-images.githubusercontent.com/8255114/90285195-b7887480-de73-11ea-9199-869ef4c3214a.png)

This is still not that much, but we also should not expect a utilization rate of 100 %.
You should note, battery capacity in quite high in this scenario:

| Capacity | Discharge power|
|-|-|
| 770 MWh | 21309.0 MW |

and there are still ~2 TWh of electricity exports.

**Comment by gplssm** [comment]
I propose to close this issue. For it seems that everything works correct. Given by the scenario conditions, there is always export to national grid which is expected to decrease demand for flexibility.
@nesnoj any objections?

**Comment by nesnoj** [comment]
> @nesnoj any objections?

Nope, thanks for checking!
