### ISSUE TITLE
line loading plot line name annotion is wrong

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#118]
![newplot (2)](https://user-images.githubusercontent.com/8255114/89102764-825c3b00-d40c-11ea-864f-26025bb6abf1.png)

I'd expected two ags names (Gemeinden) for each line (respectively group of lines) in the plot which describe start/end of the line.

**Comment by nailend** [comment]
True, I accidentially lost the multiindex by summing up. Generally I will have to use a different DF to show this information as `results_scns[scenario]['flows_txaxt']['Line loading']` is only showing the ?mean? loading from ags to ags. 
I might better use `results_scns[scenario]['flows_txaxt']['Line loading per bus']` then.
