### ISSUE TITLE
Dump and restore results per scenario using pickle

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#119]
- [x] dump pickle results, controlled by param, target e.g. `results/run/scenario/processed/`
- [x] load pickle results in `analysis()`, controlled by param: load if file exists (default) or force reanalysis
- [x] add parameter `force_new_results` (or similar) to template notebook and papermill execution function
- [x] automatically do analysis after run_scenario and include in run results
  - pro: this would save a lot of time for all of us.
  - con: if something in analysis is changed, the analysis' results will be outdated - a fact that can be easily missed and is error-prone. But I think there won't be any big changes in the next time..
  - I'd include this feature, agree @gplssm?

**Comment by gplssm** [comment]
>     * [ ]  automatically do analysis after run_scenario and include in run results
>       
>       * pro: this would save a lot of time for all of us.
>       * con: if something in analysis is changed, the analysis' results will be outdated - a fact that can be easily missed and is error-prone. But I think there won't be any big changes in the next time..
>       * I'd include this feature, agree @gplssm?

We can still keep the functionality of running `analysis()` idependently, for example while re-running the notebooks with papermill using  `force_new_results=True`. So, go for it! :rocket:
