### ISSUE TITLE
Remove obsolete default params from jupy template

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#122]
I'd remove cell 3 in the jupy template holding scenrio + run id as it is overwritten anyway.
ok?

**Comment by nailend** [comment]
is it? how do I use it then?

**Comment by nesnoj** [comment]
Yepp, as soon as you create the scenerio notebooks a new cell is created right after the 3rd..

**Comment by nesnoj** [comment]
Done
