### ISSUE TITLE
full-cycles exceed theoretical possible number of cycles

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#127]
![newplot](https://user-images.githubusercontent.com/8255114/89532365-f7a38380-d7f1-11ea-813f-6c0226960bdd.png)

I'm happy to see, that battery storages get used more in scenario ISE2050_AUT90_BAThigh

It seems like something is wrong with total cycle of small-scale battery storages. Simulating 1 month, these storage yield >2000 total cycle.
In case of a `c_rate=1`, total cycles shouldn't the theoretical limit of 372 times

**Comment by nailend** [comment]
There seems to be an error when transferring the data to the model. @nesnoj 
The scenario list contains the following values for home storage:Power|Capacity
-- | --
0,16 GW | 0,24 GWh

In the model, however, only the following arrive.
Power|Capacity
-- | --
160 MW | 1,45 MWh

**Comment by nailend** [comment]
Also I double mixed up a variable name calculating the battery_storage_figures. But this equalizes itself. Fixed it

**Comment by nesnoj** [comment]
> There seems to be a bug when transferring the data to the model. @nesnoj

Thank you @nailend! This is very critical, I opened a separate issue: #141

**Comment by gplssm** [comment]
With #142 being merged, we can take another look on total cycles of small battery storages (scneario: ISE2050_AUT90_BAThigh):

![newplot](https://user-images.githubusercontent.com/8255114/90122833-32f80200-dd5e-11ea-8849-823588319578.png)

Large-scale storages aren't used that much (-> 9 TWh exports). The problem with total cycles, more than theoretically possible, still remains. I gonna check the implementation and come back here.

**Comment by gplssm** [comment]
Investigating calculation of total cycles and utilization rate for battery storages and few things come up

![newplot](https://user-images.githubusercontent.com/8255114/90128307-faa8f180-dd66-11ea-80e7-cdd1a94e9bd0.png)


Numbers  whereof total cycles, etc. are calculated (`df_data`)
![grafik](https://user-images.githubusercontent.com/8255114/90127776-0516bb80-dd66-11ea-85d3-a9327c2454d5.png)

- [ ] Discharge for small  storages compared to available capacity is too high -> resulting total cycles of up to above 30.000 cycles are plausible -> plot is correct. But either underlying capacity or discharge is wrong
- [ ] Total cycles for entire ABW region (clicking ABW button in legend) is too high (8k large-scale; 250k small-scale). Seems like something is summed up instead of being averaged or recalculated with summarized values for entire region
- [ ] Utilization rate has to redefined. I propose something like
  ![\begin{align*}
total_{cycles} = \frac{\sum_t discharge}{capacity}
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0Atotal_%7Bcycles%7D+%3D+%5Cfrac%7B%5Csum_t+discharge%7D%7Bcapacity%7D%0A%5Cend%7Balign%2A%7D%0A)
  
  ![\begin{align*}
utilization_{rate} = \frac{tc}{tc_{max}} = \frac{1}{2} \cdot EP_{ratio} \cdot total_{hours}
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0Autilization_%7Brate%7D+%3D+%5Cfrac%7Btc%7D%7Btc_%7Bmax%7D%7D+%3D+%5Cfrac%7B1%7D%7B2%7D+%5Ccdot+EP_%7Bratio%7D+%5Ccdot+total_%7Bhours%7D%0A%5Cend%7Balign%2A%7D%0A)
  
  ![\begin{align*}
EP_{ratio}  = \begin{cases}
\frac{power\_discharge}{capacity} & \frac{power\_discharge}{capacity} \leq 1 \\
1 & \, \text{otherwise}
\end{cases}
\end{align*}
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0AEP_%7Bratio%7D++%3D+%5Cbegin%7Bcases%7D%0A%5Cfrac%7Bpower%5C_discharge%7D%7Bcapacity%7D+%26+%5Cfrac%7Bpower%5C_discharge%7D%7Bcapacity%7D+%5Cleq+1+%5C%5C%0A1+%26+%5C%2C+%5Ctext%7Botherwise%7D%0A%5Cend%7Bcases%7D%0A%5Cend%7Balign%2A%7D%0A)

**Comment by gplssm** [comment]
Did a run with latest battery paramter fixes for NEP_BAThigh full-year

![newplot(2)](https://user-images.githubusercontent.com/8255114/90155037-2342e280-dd8b-11ea-81c3-18d8d3affcd3.png)

Small batteries do not exceed theoretical ma. cycles.

The utilization rate can still be questioned with 35 cycles (large) 89 cycles (small) on average for all municipalities.
To me, it seems plausible as we still have 3 TWh of exported electricity (more than total demand) which decreases demand for flex. options and particular for those "expensive" as battery storages.

**Comment by nesnoj** [comment]
@gplssm There's no unit for param "utilization rate" in the newly adjusted storage plots. It should be %, right?

![bat3](https://user-images.githubusercontent.com/15910173/90246282-8fc5ec00-de34-11ea-8b41-98d73d0bbdfe.png)

**Comment by gplssm** [comment]
True! Seems like without a unit for "Utilization Rate", secondary y-axis is not shown. I gonna add it.
