### ISSUE TITLE
heat storage utilization in "nostor"-scenario

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#129]
While looking on battery utilization, I've analyzed ISE2050_PTHisenostor. According to the scenario table, this scenario shouid have 0 % heat storages. Nevertheless, heat storages are used.

![newplot(1)](https://user-images.githubusercontent.com/8255114/89618898-4baf7600-d88d-11ea-8783-e449ce129326.png)

I understood 0 % heat storages equals zero capacity

1. Is my understanding right?
2. If (1), why do we see heat storages being used?

**Comment by nesnoj** [comment]
> I understood 0 % heat storages equals zero capacity
> 
> 1. Is my understanding right?

No
- centralized storages should be zero except for Dessau (already existing), this seems to be ok
- decentralized storages: there's a minimum capacity for all radiator-based HP-systems as they are technically required, cf. scenario table "0d. Szenariodaten_ABW_export" -> param "storage->th_dec_pth_storage->general->capacity_spec"

The actual numbers we're using is subject to #43 - still TBD. We should talk about who is going to take care of this..

**Comment by gplssm** [comment]
> > I understood 0 % heat storages equals zero capacity
> > 
> > 1. Is my understanding right?
> 
> No
> 
>     * centralized storages should be zero except for Dessau (already existing), this seems to be ok
>       Does it make sense to change this?
> 
>     * decentralized storages: there's a minimum capacity for all radiator-based HP-systems as they are technically required, cf. scenario table "0d. Szenariodaten_ABW_export" -> param "storage->th_dec_pth_storage->general->capacity_spec"
> 
> 
> The actual numbers we're using is subject to #43 - still TBD. We should talk about who is going to take care of this..

Thanks for the explanations! As it is not a bug, I'll gonna close this issue. Parameter adjustsments will be discussed in #43
