### ISSUE TITLE
There is no SinkDSM

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#13]
See placeholder [here](https://github.com/windnode/WindNODE_ABW/blob/dev/windnode_abw/model/region/model.py#L646-L652)

**Comment by nailend** [comment]
added SinkDSM [here](https://github.com/windnode/WindNODE_ABW/blob/dev/windnode_abw/model/region/model.py#L649-L674)

parameter: delay_time & shift_interval must be int !!!


added calculation functions to convert capacity data [here](https://github.com/windnode/WindNODE_ABW/blob/6d32fdf658b91df4bcd507f7ffcdf72bb4f11539/windnode_abw/model/region/tools.py#L486-L516)

added DSM params to config file [here](https://github.com/windnode/WindNODE_ABW/blob/6d32fdf658b91df4bcd507f7ffcdf72bb4f11539/windnode_abw/scenarios/status_quo.scn#L125-L135)

normal sink will only be created if SinkDSM is disabled
[here](https://github.com/windnode/WindNODE_ABW/blob/6d32fdf658b91df4bcd507f7ffcdf72bb4f11539/windnode_abw/model/region/model.py#L163)
