### ISSUE TITLE
Results single scenario: Completion

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#130]
To finish the single scenario notebook template, some last work needs to be done (apart from plausibility):
- [x] Check order of sections
  - [x] Merge 9 (Energy Exchange) into 3 (Autarky)?
- [x] Same order of municipalities in all plots (e.g. in alphabetic order)
- [ ] Update header
  - [x] Add intro text
  - [ ] Add links referring RTD docs (ideally to sub-parts)
  - [x] Add TOC (without jupyter extension, [example](https://nbviewer.jupyter.org/gist/wolfbunke/7659fbc22b9d72f0cda8dc544d1f537e))
  - [x] Add note on nb trust
- [x] Add required notes (e.g. to DSM plots)
- [x] Check plots
  - [x] Titles, Legends, Axes (+units)... ok?
  - [x] Colors & Colormap
  - [x] Obsolete plots that can be removed?
- [x] #122
- [x] refurbishmend of nb post autarky #139
- [x] Map with municipalities names in 1
- [x] Add a note at top of the notebook to be patient as the rendering may take some time

**Comment by nailend** [comment]
@nesnoj  where do you think the 'rendering note' is place best? Directly in the first cell?

**Comment by nesnoj** [comment]
Sounds jut
Also, please add a note that the notebook needs to be trusted to be shown correctly (cf. note in the docs) .
