### ISSUE TITLE
refurbishmend of nb after #135

### ISSUE THREAD

**Issue by nailend** [windnode/WindNODE_ABW#139]
As soon as this is done, plots in single-scenario jupy nb might need refurbishment, e.g.
- [x] percentage of autark hours.
- [x] the notes need to be adjusted according to new definition.
- [x] add equations.

**Comment by nesnoj** [comment]
I added a checkbox to #130 which is the superordinate issue on completion.

**Comment by nesnoj** [comment]
Unsure whether still required or not - not in the coffin yet...
