### ISSUE TITLE
LCOH seem unrealisticly high

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#158]
![newplot (1)](https://user-images.githubusercontent.com/8255114/90344180-67e2ae00-e017-11ea-98af-10a46f06a5a2.png)

Mainly due to: Gas heating, gas district heating, oil heating

Tested with NEP_RE-

**Comment by gplssm** [comment]
Indeed, calculation of variable cost for natural gas heating (and for all other technologies using natural as commodity) is wrong. 
The reason is that cost for natural gas are 182 €/MWh_th in `results_scns[scenario]['parameters']['Parameters el. generators']` and `results_scns[scenario]['parameters']['Parameters th. generators']`
Opex_ar for natural in `regions_scns[scenario].tech_assupmtions_scn` is correct.

Hence, I gonna search for the bug

**Comment by gplssm** [comment]
Ok ok, everything is correct!

Explanation: The 182 €/MWh_th result of a mixed price of natural gas and synthetic methane which comes at cost of 289 €/MWh_th. 
We assume a share of methane of 55 % by 2035. Also for gas heating systems. This makes them very costly and we enforce these cost by assuming a certain share of houses are supplied by heat from gas heating.

Options

1. Leave it as it is and communicate assumptions of 55 % percent synthetic methane also for heating in 2035 (I guess this is not in line with NEP 2035 assumptions)
2. Exclude methane use for heat generation 
3. Overthink the entire assumption of synthetic methane in 2035

Sorry @nesnoj, I need to discuss this with you again.

**Comment by nesnoj** [comment]
Thanks for diggin'!

Yepp, I think that the current synth. methane increase is too optimistic.

> * Leave it as it is and communicate assumptions of 55 % percent synthetic methane also for heating in 2035 (I guess this is not in line with NEP 2035 assumptions)

I wouldn't do that neither.

> * Exclude methane use for heat generation

Hmmm...

> * Overthink the entire assumption of synthetic methane in 2035

Let's stick with some literature: Even in the (max) 95% emission reduction scenario [UBA2019](https://www.umweltbundesamt.de/sites/default/files/medien/1410/publikationen/2019-04-15_cc_12-2019_roadmap-gas_2.pdf) p49 there's (nearly) zero synth. methane in 2035 (2050: ~95%)
Money quote:
"In the energy sector, the use of gas fulfils an important bridging function. The use of gas in CHP installations hardly declines at all up to 2030 and even rises to some extent. In 2050, however, only very small amounts of gas remain to balance the fluctuations of renewable energies in the system. " (p30)

Also, I quickly estimated the share according to NEP: on p49 they state 0,75 TWh power2methane, compared to 2000 PJ in 2030 (UBA above) it's nothing. even if you included p2H2 it was only ~3%.

I could live with setting it to zero.
It might be more a matter of conviction...

**Comment by gplssm** [comment]
Seems to be very clear that we overestimate methane. I vote for neglecting it

**Comment by nesnoj** [comment]
:+1: With regard to the runs it is the first thing I would do today..

**Comment by gplssm** [comment]
I would say, methane share in 2035 and HP cost parameter for ASHP are the last changes we can implement. One final run and :rocket:
