### ISSUE TITLE
biogas produces similar CO2 emissions per kWh as CCGT

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#159]
This seems implausible

![newplot (2)](https://user-images.githubusercontent.com/8255114/90344229-f820f300-e017-11ea-8de2-3200a2871843.png)

Tested with NEP_Re-

### Next steps

- [ ] Check emission factor of biogas

**Comment by nesnoj** [comment]
The numbers for biogas seem to be totally wrong, I calculate 426 MWh * 27,47 kg/MWh = 11700t
I'll check this...

**Comment by gplssm** [comment]
> The numbers for biogas seem to be totally wrong, I calculate 426 GWh * 27,47 kg/MWh = 11700t
> I'll check this...

But don't forget emissions from the commodity `comm_biogas`. Although these are not considered in the model, right now they are considered in the ex-post analysis

**Comment by nesnoj** [comment]
> But don't forget emissions from the commodity `comm_biogas`. Although these are not considered in the model, right now they are considered in the ex-post analysis

Yes, that's exactly what this is all about! Bio contains emissions from the plant AND the comm.

**Comment by nesnoj** [comment]
I'm currently testing....

**Comment by gplssm** [comment]
> > But don't forget emissions from the commodity `comm_biogas`. Although these are not considered in the model, right now they are considered in the ex-post analysis
> 
> Yes, that's exactly what this is all about! Bio contains emissions from the plant AND the comm.

I don't get it. If you want to discuss, we can have a call

**Comment by nesnoj** [comment]
> I don't get it. If you want to discuss, we can have a call

We consider emissions caused by bioplants and these are given in the tech table, ready to b used as they are for entire biogas production. That's at least how I understood them.. but I'll re-check.
The commodity emissions reflect the same thing again from a buyer's perspective so I kicked them out in #162.
Gimme a buzz if you like

**Comment by nesnoj** [comment]
I re-checked UBA and discovered inconsistencies -> the 60,44 contain upstream chain emissions only, also without weighting of the gas type. In the end, correct number is 153,9 kg/MWh for SQ and subsequently 70 kg/MWh for 2035. The latter results in 30kt CO2 which is similar to PV ground. Agree?
