### ISSUE TITLE
heat pump invest costs might be assumed too high 

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#165]
Looking at LCOH in `ISE_RE-` reveals that only HP are responsive for ~50 % of costs.

![newplot (3)](https://user-images.githubusercontent.com/8255114/90422999-01fc3200-e0bc-11ea-9390-a26a4bf4c37f.png)

It's true that HPs also generate ~50 % of heat demand, but other researchers assume way lower costs.

| | Air-source HP | Ground-source HP |
|-|-|-|
|WindNODE_ABW | 8.500 €/kW | 1.400 €/kW |
| [PyPSA-eur-sec](https://github.com/PyPSA/pypsa-eur-sec/blob/master/data/costs.csv) (2030) | 1.050 €/kW | 1.400 €/kW | 

PyPSA-eur-sec takes it assumptions from "Palzer thesis".

At least we agree on ground-sourced heat pumps :+1:

**Comment by gplssm** [comment]
I think a tracked it down to a mistake in data transfer.

For WindNODE_ABW, we take technical and economic data from [DEA](https://ens.dk/sites/ens.dk/files/Analyser/technology_data_catalogue_for_individual_heating_installations.pdf) (ASHP: p. 89, GSHP: p. 93)

There, cost are given per unit instead of per kW_th. Assumed unit size is 10 kW_th.

Values given:

ASHP: 8500 €/unit
GSHP: 14000 €/unit

For GSHP it is correctly translated to costs per kW and agrees nicely with Palzer (maybe he did the same!?).
For ASHP conversion to €/kW didn't take place and we use costs per unit and apply the to per kW.

@nesnoj can you change costs for ASHP to 850 €/kW_th? This has to be done for 2035 and 2050

**Comment by nesnoj** [comment]
Ooops, wtf?
Sure..
