### ISSUE TITLE
missing ags values of "Batteriepseicher nach Gemeinde"

### ISSUE THREAD

**Issue by nailend** [windnode/WindNODE_ABW#172]
There are missing values of the parameter discharge and charge for battery-storages "small" of ags=small/15082256 resulting in NaNs for further use.
in scenario ISE_DSM+_BAT+_PTH+
- results_scns['ISE_DSM+_BAT+_PTH+']['results_axlxt']['Batteriespeicher nach Gemeinde']

although these values exist in scenario ISE
- results_scns['ISE']['results_axlxt']['Batteriespeicher nach Gemeinde']

**found after forced new results with branch: feature/#64_multiple_scenarios_results**

**Comment by gplssm** [comment]
Can't very NaN values. Actually, AGS 15082256 isn't in the index (only for "large"). Scenario used: ISE_DSM+_BAT+_PTH+

![grafik](https://user-images.githubusercontent.com/8255114/90522425-fa946180-e16b-11ea-9e88-dd4fd74543c1.png)

But, this was done using DB dump `windnode_db_200727.backup`.

Testing with latest DB dump `windnode_db_200817.backup`.

![grafik](https://user-images.githubusercontent.com/8255114/90522834-7abac700-e16c-11ea-8c58-7d004a9e816f.png)

Same!

One point is still interesting: why do we find the key in scenario ISE? I can verify this:

![grafik](https://user-images.githubusercontent.com/8255114/90523209-e735c600-e16c-11ea-8bde-27836abc5f00.png)

I guess keys for all MUNs are added during [zero filling](https://github.com/windnode/WindNODE_ABW/blob/a425a9d9007c151a6205fc5a60591a6e5a58fb96/windnode_abw/analysis/tools.py#L791-L802).

**Comment by nesnoj** [comment]
Unsure whether still required or not - not in the coffin yet...
