### ISSUE TITLE
Add references to bibfile

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#195]
The sources from the model documentation need to be added to the [bib references](https://github.com/windnode/WindNODE_ABW/blob/feature/%23195_bib_references/docs/references.bib).

- [x] add working branch on RTD to make it easy to check the results in the [RTD documentation](https://windnode-abw.readthedocs.io/en/feature-195_bib_references/zbibliography.html) immediately @nesnoj 
- [x] add literature from "Kosten Emissionen Wirkungsgrade" @nailend 
- [x]  add literature from "Szenarien_Eingangsdatenherleitung" @nailend 
- [x]  add literature from "Szenarien_Ergebnisse_Prognosen_2050" @nailend 
- [x] add IWU-Study to bib @nailend 
- [x]  add literature from "Modell Methodik Daten" @ShaquilleH

**Comment by nailend** [comment]
@nesnoj I cant find the IWU-Study, which we used for the new building and renovation parameters. Do you have a link?

**Comment by nesnoj** [comment]
> @nesnoj I cant find the IWU-Study, which we used for the new building and renovation parameters. Do you have a link?

This one? `.../143_WindNODE/08-Know-How/Verbrauch/2015_DE_TABULA_TypologyBrochure_IWU.pdf`
Or on the web: https://www.iwu.de/fileadmin/publikationen/gebaeudebestand/episcope/2015_IWU_LogaEtAl_Deutsche-Wohngeb%C3%A4udetypologie.pdf
