### ISSUE TITLE
results from each scenario in a Jupytor Notebook

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#27]
|# | Größe | Einheit | Plot/Tabelle | Kommentar | Done? |
|-------|----------|-----------|-----------------|-----------------|-----------------|
|1 | LCOE (Electricity, Heat) | divers | table | TODO #35  |x |
|2 | CO2 Emissionen| divers | table | 1) absolute, 2) year X compared to SQ, 3) compared to 1990 | 1) x |
|3 | Required Area | divers | Geoplots | absolute, relative | x|
|4| Autarky (balance)  | % | Bar plot | rel suppy/demand,  | x |
|5| Autarky (time) | hours,  % | Bar plot | hours a month/year | x |
|6| energymix | MWh | Barplot, areaplot (+ table) | generatio per technology | x |
|7| CO2 emissions per technology (elec. + heat) | tCO2 | stacked bar plot (elec/heat)| full year, 2 bars, technology stacked | x |
|8| rel use of flexibility options | | bar plot / boxplots | Ausgespeicherte Energie (Speicher), Durchgelaufene Energie (DSM) | |
|9| line loadings | % | bar plot | Ein Wert je Leitung | |
|10| line loadings | % | box plot | Median, whisker(min/max), full year | |
|11|  | % | Gridmap | (optional), Einfärbung nach Auslastung, pandapower| |
|12| LCOE+LCOE | €/Mwh | stacked bar plot jeweils für LCOE und LCOH | Anteilig für je Technologie. Daten in `results_scns[scn_id]['results_t']["LCOE"]` zu finden |x |

**Comment by nesnoj** [comment]
@nailend I've added some plotting functions in [draw.py](https://github.com/windnode/WindNODE_ABW/blob/dev/windnode_abw/tools/draw.py) incl. plotting geodata, you may want to make use of parts...

**Comment by nesnoj** [comment]
@nailend Feel free to create a new branch from `feature/#18-highlevel-results` for your tasks, cf. #26

**Comment by nailend** [comment]
nr. 1:
- shall this be accumulated value are specific for every district?
- no costs for LCOE available yet... TODO
- rel CO2 emission to SQ: where do I get the SQ emissions from? isn't it a different scenario?
- total area required or for each technology? == highlevel-results

**Comment by nesnoj** [comment]
> * shall this be accumulated values or specific for every district?

Aggregated values for ABW should be fine. Land use (Flächenbedarf) should be given per mun but this is part of #31. You may skip this for now.

> * no costs for LCOE available yet... TODO

?

> * rel CO2 emission to SQ: where do I get the SQ emissions from? isn't it a different scenario?

They result from the SQ analysis which should be done before. To allow for multiple scenarios, see #39.

> * total area required or for each technology? == highlevel-results

Not sure what you mean here, I guess the land use again (see above, #31)

**Comment by nesnoj** [comment]
As we will update the table above successively, I added a column "Done?" to the table above to track your progress..

**Comment by nesnoj** [comment]
The params and numbers of abs.+rel. areas required by wind+pv will change when #57 is merged, the notebook need to be adjusted. I'll come back to you with some ideas+comments on what needs to be done.

**Comment by nesnoj** [comment]
Ok, some updates:

**RES Landuse: 1 scenario**
- geoplots: absolute available areas per mun and technology in ha (for pv_roof_small, pv_roof_large, pv_ground, wind)
- barplot: relative area use of pv_roof for entire region (highlevel) in %
  - total
  - small
  - large
- barplot: relative area use of pv_ground for entire region (highlevel) in %
  - All 7 `'Area required rel. PV ground XXX'`
- barplot: relative area use of wind for entire region (highlevel) in %
  - All 5 `'Area required rel. wind XXX'`

If the 3 barplots above fit smoothly into a single plot, go for it.

I saw that I didn't update the units dict in #57, I'll fix this.

**RES Landuse: Scenario comparison**
(I'll add this to the list in #64)

**Other**
Furthermore, I think it'd be good to have more general information on the scenario setting, e.g. visualization of the spatial mismatch between supply and demand, so 2 plots just prior to the reqd. areas
  - installed RE capacity per mun and technology (geoplots for pv_roof, pv_ground, wind, bio, hydro, rest) similar to [this one](https://github.com/windnode/WindNODE_ABW/blob/1454a09f4f8135e316f4d41ed5cef3e4a051efa1/windnode_abw/tools/draw.py#L263-L293).
  - cumulative demand per mun and sector (geoplots for res, rca, ind)

Does this make sense to you?
