### ISSUE TITLE
Add investment mode for lines

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#32]
As line caps are not sufficient for some scenarios with high share of RE, there's a need for grid extension.

Branch: feature/add_line_investment

- [x] Does Link component support investment mode? Yes!
- [x] Check performance: 6 months run with scn dev/future
  - w/o line invest: 35 min, 17.6 GB RAM
  - w/ line invest: 40 min, 18.5 GB RAM
- [x] Add params to tech table from [[1]](https://www.mdpi.com/1996-1073/12/11/2091/pdf), [[2]](https://www.uni-flensburg.de/fileadmin/content/abteilungen/industrial/dokumente/downloads/veroeffentlichungen/forschungsergebnisse/20190426endbericht-openego-fkz0325881-final.pdf) (S. 35) and [[3]](https://link.springer.com/article/10.1007/s11367-011-0335-1)
- [x] Create, upload and link new DB dump
- [x] Calculate eq. periodic costs using spec. costs, lengths from `Region.lines`
- [x] Add costs & emissions to model (replace cfg params)

Integrate extension measures and costs in #18.

**Comment by nesnoj** [comment]
All done, you may want to use the results in #18 @gplssm

One remaining question:
Will the investment (annuity/EPC) be made per direction (twice) for each Link?

**Comment by nesnoj** [comment]
I tested with minimum example and invest will take place for both directions separately.
The investments

**Comment by nesnoj** [comment]
I tested with minimum example and invest will take place for both directions separately.

The investments are stored in the results scalar Series like
`((('line_0', 'b_0'), 'invest'), INVEST1) ((('line_0', 'b_1'), 'invest'), INVEST2)`

To avoid being counted twice, use the larger of both values.

**Comment by nesnoj** [comment]
I tested with minimum example and invest will take place for both directions separately.

The [epc_costs](https://github.com/windnode/WindNODE_ABW/blob/f2705cf3287d08a92e81e90eb70ce56dded7e6f7/windnode_abw/model/region/model.py#L416-L428) I used are the final costs which already incorporate the length.

The line extensions (in MW) are stored in the results scalar Series like
`((('line_0', 'b_0'), 'invest'), EXTENSION1_MW) ((('line_0', 'b_1'), 'invest'), EXTENSION2_MW)` and refer to the extended power (non-monetary!). Not sure if those are already exported..
**Note:** To avoid being counted twice, use the max of all values in both directions.

Calculate the monetary investment by either
1. directly using the 'investment_ep_costs' from results' `params_flows.csv` (in €/MW, already include line lengths) multiplying with the line extensions from above or
2. re-calculating (may be easier) the costs using length-spec. annuity from tech DF and line lengths from `region.lines`, again multiplied with the line extensions from above

**Comment by nesnoj** [comment]
Reminder: Are there `Link` flows in both directions at the same time?

**Comment by gplssm** [comment]
Isn't this already merged into dev? Can we close it? @nesnoj

**Comment by nesnoj** [comment]
Yes it is, but didn't close as I wanted to remind you to consider the bidirectional investment in the ex post calculations #36, see my [post above](https://github.com/windnode/WindNODE_ABW/issues/32#issuecomment-643733682). Are you finished with that?

**Comment by nesnoj** [comment]
Also, you wanted to check if there're flows in both directions at the same time in the `Link` component.

**Comment by gplssm** [comment]
Ok, I'll gonna do that! Not finished yet :smirk:

**Comment by nesnoj** [comment]
Have you checked for bidirectional flows @gplssm ?

One more question: Usually lines are not operated above a certain loading (backup capacity), e.g. 60%. I propose to neglect this issue?!

**Comment by gplssm** [comment]
> Have you checked for bidirectional flows @gplssm ?
> 

Took me some time to go thorugh the points...
https://github.com/windnode/WindNODE_ABW/pull/75#issuecomment-663074278

> One more question: Usually lines are not operated above a certain loading (backup capacity), e.g. 60%. I propose to neglect this issue?!

hmm...

**Comment by nesnoj** [comment]
> > Have you checked for bidirectional flows @gplssm ?
> 
> Took me some time to go thorugh the points...
> [#75 (comment)](https://github.com/windnode/WindNODE_ABW/pull/75#issuecomment-663074278)

No worries, I can do it.

> > One more question: Usually lines are not operated above a certain loading (backup capacity), e.g. 60%. I propose to neglect this issue?!
> 
> hmm...

This could be easily done ex post, let's decide later #83.

**Comment by nesnoj** [comment]
> > > Have you checked for bidirectional flows @gplssm ?
> > 
> > 
> > Took me some time to go thorugh the points...
> > [#75 (comment)](https://github.com/windnode/WindNODE_ABW/pull/75#issuecomment-663074278)
> 
> No worries, I can do it.

I've put a breakpoint in [L375 of analysis/tools.py](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/analysis/tools.py#L375) where the line flows are extracted from the raw data for the first time and checked with
```
line_flows = results_raw.loc[:,
                    results_raw.columns.get_level_values(level_flow_in).str.match(bus_pattern)
                    & results_raw.columns.get_level_values(level_flow_out).str.match(line_pattern)].add_suffix('_TO').join(
results_raw.loc[:,
                    results_raw.columns.get_level_values(level_flow_out).str.match(bus_pattern)
                    & results_raw.columns.get_level_values(level_flow_in).str.match(line_pattern)].swaplevel(i=0, j=1, axis=1).add_suffix('_BACK')
)

line_flows = line_flows.reindex(sorted(line_flows.columns), axis=1)
```
to have them side by side.
At first glance, I cannot see any bidirectional flows, looks good.

@gplssm As you came up with this question, please close if you're fine with this approach.
