### ISSUE TITLE
efficiency of GuD has to be considered time-dependent 

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#33]
[Right now](https://github.com/windnode/WindNODE_ABW/blob/ca3a1fb58391b00955e7f3f5707585802a116171/windnode_abw/analysis/tools.py#L636-L641) maximum electrical and thermal conversion efficiency is considered when calculating CO2 emission for GuD separately for heat and electricity.

The general idea is to account for the CO2 emissions related to heat and electricity produced by a GuD. Since it is modeled as ExtractionCHPTurbine, both efficiencies change over time. Thus, we need to account for this.
The idea to do this it to 

 CO2_{heat} = P_th / (P_th + P_el) *  P_gas * co2factor_gas
 CO2_{electricity} = P_el / (P_th + P_el) *  P_gas * co2factor_gas

**Comment by nesnoj** [comment]
There's another problem with the BHKW: The coupled operation is not considered in emission calc: They are calculated using constant sys eff. for el./th. only (var_emis=generation * sys_eff_el * co2factor_gas) -> no split between th+el.
