### ISSUE TITLE
add ex-post costs calculation to results processing

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#35]
Extend the results post-processing by cost calculations. for example calculate the following numbers (and feel free to extend):

- [x] Gesamtkosten in €
- [ ] Stromversorgungskosten in €/MWh
- [ ] Wärmeversorgungskosten in €/MWh

Adopt from [calculation CO2 emissions](https://github.com/windnode/WindNODE_ABW/blob/ca3a1fb58391b00955e7f3f5707585802a116171/windnode_abw/analysis/tools.py#L712-L727) and implement the following formula

costs = P_inst * (annuity_factor + opex_fix) + E_gen * opex_var + E_commodity * opex_var_commodity

Note, in `region.tech_assumptions` a annuity can be found, but it's not the annuity_factor. Seems like it's related to the capacity of the whole region.

**Comment by nesnoj** [comment]
> costs = P_inst * (annuity_factor + opex_fix) + E_gen * opex_var + E_commodity * opex_var_commodity
> 
> Note, in `region.tech_assumptions` a annuity can be found, but it's not the annuity_factor. Seems like it's related to the capacity of the whole region.

Not sure what u mean by annuity_factor, opex_fix is already given in €/MW/a and can be used straighforward.

**Comment by gplssm** [comment]
> > costs = P_inst * (annuity_factor + opex_fix) + E_gen * opex_var + E_commodity * opex_var_commodity
> > Note, in `region.tech_assumptions` a annuity can be found, but it's not the annuity_factor. Seems like it's related to the capacity of the whole region.
> 
> Not sure what u mean by annuity_factor, opex_fix is already given in €/MW/a and can be used straighforward.
> 
> PS: The annuity given in `region.tech_assumptions` is the annuity calculated from CAPEX & WACC.

You're right, the annuity_factor was misleading. We can simply take the annuity already present in `region.tech_assumptions` and calculate total cost by

costs = P_inst * (annuity + opex_fix) + E_gen * opex_var + E_commodity * opex_var_commodity
