### ISSUE TITLE
available area for PV ground exceeded by far/ sometimes inf

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#44]
For some regions, the available area is exceeded by far in the "dev future" scenario.
In addition, for PV ground without agricultural areas sometimes `inf` results, because an area of 0 ha is available. 

@nesnoj could you please re-check this?

**Comment by nesnoj** [comment]
Could you please be more specific?
Which scenario version are you running? Current dev/future in `feature/#18-highlevel-results`?
And did you encounter these problems using `run_scenario.py` or `run_analysis.py`?

**Comment by gplssm** [comment]
> Which scenario version are you running? Current dev/future in feature/#18-highlevel-results?

Yes, in principle. Now, #26 is merged into dev. It also occurs there. And yes, it is testing scenario `future`

> And did you encounter these problems using run_scenario.py or run_analysis.py?

`run_analysis.py`

I would just like to take a look on that together with you, because I guess this is the way faster way resolving it.

**Comment by gplssm** [comment]
In addition, results_scns['NEP2035']['results_axlxt']['Area required rel.']["PV ground hard"] contains some `nan`s. Remove these by either setting to zweo (`fillna(0)`) or something different. Depends on if `nan`s are expected. This is more a note for @gplssm
