### ISSUE TITLE
pygraphviz doesnt build in binder

### ISSUE THREAD

**Issue by nailend** [windnode/WindNODE_ABW#50]
I just tried to launch the  [scenario-notebook](https://github.com/windnode/WindNODE_ABW/blob/feature/%2327-scenario-results/windnode_abw/jupy/scenario_analysis.ipynb) on [binder.org](https://mybinder.org/) resulting in an ERROR.

> ERROR: Failed building wheel for pygraphviz

conda install pygraphviz might help in the setup.py

**Comment by nailend** [comment]
#22 #10

**Comment by nesnoj** [comment]
Not sure if this is possible on binder, but we solved similar problems on RTD in the past by mocking some packages ([example](https://github.com/openego/ding0/blob/24c4d3a881adaa1e3cea2c8fe5c7d070d4c61fb5/doc/conf.py#L178-L186)). And pygraphviz is not required for the notebook...
