### ISSUE TITLE
cost for district heating not considered in ex-post costs calculation

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#52]
Depending on what's the unit of `opex_var` in this case, maybe scale `opex_var` with total heat demand central.
@nesnoj could you please repeat how `opex_var` are defined in this case?

**Comment by gplssm** [comment]
It is defined as €/MWh heating demand in district heating networks

**Comment by nesnoj** [comment]
Actually, it's €/kWh

**Comment by nesnoj** [comment]
I'm sorry, the raw data is per kW(h) indeed but costs are converted to MW(h) as you can see [here](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/tools/data_io.py#L468-L482) (costs only, as emissions in g/kWh equal kg/MWh).

**Comment by gplssm** [comment]
> I'm sorry, the [raw data ](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/config/db_models.py#L368-L392)is per kW(h) indeed but costs are converted to MW(h) as you can see [here](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/tools/data_io.py#L468-L482) (costs only, as emissions in g/kWh equal kg/MWh).

I saw that emissions are in kg/MWh while adding co2 certificate costs in #42. Do you see anything I should change?

**Comment by nesnoj** [comment]
> Do you see anything I should change?

`_calculate_supply_costs()` looks correct at least.
Without having a complete overview where you made use of the costs units, I think no.
