### ISSUE TITLE
execute results notebook for all scenarios managed by paper mill

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#77]
With paper mill, we can parametrize notebooks with the scenario name and execute notebooks for all scenarios

- [x] Convert notebook from #27 to template using [parameters](https://papermill.readthedocs.io/en/latest/usage-parameterize.html)
- [x] Write a function that creates a notebook for each scenario (use existing lists!) and save executed notebook to desired path
- [x] (optional) Add multiprocessing, if not too much effort

Once, #27 is done, this can be started. Best would be to move the template notebook

**Comment by gplssm** [comment]
How to execute the in parallel: https://andrewm4894.com/2019/04/27/parallel-jupyter-notebooks/

**Comment by gplssm** [comment]
Works. Tested with a simple example notebook.

Use it for single scenario

```
create_scenario_notebook("NEP2035",
                         '2020-07-24_104145_1month',
                         "/home/guido/git/WindNODE_ABW/windnode_abw/jupy/scenario_analysis_test_template.ipynb")
```

or for multiple scenarios using multi processing (in this case all)

```
create_multiple_scenario_notebooks(
    "all",
    '2020-07-24_104145_1month',
    template="/home/guido/git/WindNODE_ABW/windnode_abw/jupy/scenario_analysis_test_template.ipynb",
    num_processes=None
)
```

Remaining todos

- [ ] Parametrize cell with `scenario` and run_timestamp, once #27 is finished

**Comment by nesnoj** [comment]
Note: If you want to see the output/log of what's happening, you gotta setup the logging in your initial script where you call `create_scenario_notebook()` or `create_multiple_scenario_notebooks()` using.
```
from windnode_abw.tools.logger import setup_logger
logger = setup_logger()
```
