### ISSUE TITLE
include notebooks into RTD documentation

### ISSUE THREAD

**Issue by gplssm** [windnode/WindNODE_ABW#78]
The Sphinx extension [nbsphinx](https://nbsphinx.readthedocs.io) integrates notebooks in Sphinx docs. The normal workflow includes execution of a notebook. Because this takes too long for all scenarios of WindNODE_ABW, it is not an option. Execution can be bypassed and notebooks can rendered from executed notebooks.
As the size and number of notebooks and changes made to these would grow the size of the repo, @nesnoj and I decided not to commit executed notebooks to this repo.
Instead, we are thinking of creating a separate repo to only store executed notebooks. Git tags could help to manage versions.

Btw, Binder is not really an option because of computational limitations and the need to store the results data somewhere publicly accessible.

Tasks

- [x] Check how notebooks from external sources can be included, i.e. [nbsphinx-link](https://github.com/vidartf/nbsphinx-link) **We do it differently**
- [x]  Check if (even anonymous) [gists](https://pypi.org/project/python-gist/) are a good alternative to a github repo
- [x] May it is an option to convert notebooks to `.rst` and render from there via [sphinx include](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include) **NOT**

**Comment by gplssm** [comment]
Updated tasks after some research, prototyping and re-thinking of it

- [ ]  Write function to parse directory "notebooks" and include "..toc::" direct on the top and write everything to create single_scenario_results.rst
- [ ] Remove unused content from .ipynb template and save it in a separate issue for @nailend
- [ ] Adjust heading levels in .ipynb template such that they are aligned with TOC
- [ ] Remove static notebook top heading and replace it dynamically with scenario name extracted from file name using `{{ env.doc2path(env.docname, base=None) }}`. Read in [prolog and epilog](https://nbsphinx.readthedocs.io/en/0.3.0/prolog-and-epilog.html) of nbsphinx
- [ ] Add executed-notebook-to-publish-on-gist script/function for uploading notebooks created with papermill
- [ ] Add function to `conf.py` that downloads executed notebooks from gist

**Comment by gplssm** [comment]
In general, the above ticked tasks are done. Some things done differently

- Using Zenodo instead of gist.github.com because GitHub limits max. file size to 100 mb (we have ~140 mb NBs)
- Top heading in each notebook isn't replaced with jinja templating
- no automatic upload script so far for executed `.ipynb` NBs, simple drag+drop on Zenodo is ok

In general, the NBs showing results for each scenario can be integrated into the documentation (see [on the example of two NBs](https://windnode-abw.readthedocs.io/en/feature-78-display-notebooks-in-docs/)). But it might not work with all NBs. I we could run into problems because of [resource limits of RTD](https://docs.readthedocs.io/en/stable/builds.html), which limits each build to 15 min.
[First build failed](https://readthedocs.org/projects/windnode-abw/builds/12013049/) because of other reason and the [second try ](https://readthedocs.org/projects/windnode-abw/builds/12013240/) ran into the resource limits

I see two options to get around this

1. Somehow reduce file size of `ipynb` dramatically (down to ~20...30 %)
2. Use `.html` exports of NBs and include them statically (at least 140 mb -> 50 mb)

**Comment by gplssm** [comment]
I found 5 figures causing 5/6th of the file size

- 3.3 Autarky municipalities: 13.6 MB
- 4.3 Timeseries: 12 MB
- 7.2 Line Loading Distribution: 46 MB
- 8.3.1 Activation: 22 MB
- 8.3.3 DSM Timeseries: 26 MB

Executed notebooks (`.ipynb`) require 19 to 22 Mb disk space after removing these figures.
Still, the docs build process fails on RTD.

**Comment by nesnoj** [comment]
>     * 7.2 Line Loading Distribution: 46 MB

Does the data or the plot itself consume that much space? I'd assume that the full data is stored somewhere in the plot JS?
We could use a different renderer to make the largest plots static, e.g. svg, example ([source](https://plotly.com/python/renderers/)):
```python
import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3])],
    layout_title_text="A Figure Displayed with the 'svg' Renderer"
)
fig.show(renderer="svg")
```

> Still, the docs build process fails on RTD.

Still because of the build time?
