### ISSUE TITLE
CCGT of Dessau missing in results' installed el. caps

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#80]
The CCGT of Dessau is missing in `results_scns['NEP2035']['parameters']['Installed capacity electricity supply']` due to missing `nom_value` in the flow params (only nom. th. power is set) which is extracted by [`extract_flow_params()`](https://github.com/windnode/WindNODE_ABW/blob/be1e0a8c4f6d5335c5680a6005ef4dc420d0d0e7/windnode_abw/analysis/tools.py#L466).

As the el. gen. is flexible in the model, the value might be set manually right below [this line](https://github.com/windnode/WindNODE_ABW/blob/be1e0a8c4f6d5335c5680a6005ef4dc420d0d0e7/windnode_abw/analysis/tools.py#L927) using `capacity_special.at['15001000', 'gud'] = gud_cfg['nom_el_power']` (requires this param to be included in all scenario files).

Also, this would fix the calculation of co2 and costs which I assume to be wrong for the mun of Dessau.

@gplssm @nailend Are you fine with this manual fix?

**Comment by nailend** [comment]
I do not see any problems with that! thx

**Comment by nesnoj** [comment]
I did not add it to the scenario files, but inserted **manually** as it is contained with this capacity in all scns anyway.
