### ISSUE TITLE
Wording and calculation of autarky

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#85]
1. Currently we use different wording: “Autarky” and “Self-consumption”
2. The balance- and time-related numbers are calculated differently: [1](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/analysis/tools.py#L1319-L1324), [2](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/analysis/tools.py#L767-L771), [3](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/analysis/tools.py#L1256-L1262)

Let's discuss!

**Comment by nailend** [comment]
oh, apperently I misinterpretated the "self-consumption" as an absolute value (energy amount) and therefore also set the wrong UNITS. As of this, I would suggest the term "autarky" for relative values!

There seems to be a difference in the calculation except for the formula as I exclude import AND export from demand and supply in "Autarky". Whereas in 'highlevel' only the 'import' is exclude via the [reciprocal calculation](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/analysis/tools.py#L1319-L1320] and the export is still included in the [demand](https://github.com/windnode/WindNODE_ABW/blob/038d97dbd7f10d704d5b42df7bddd0affdc8445c/windnode_abw/analysis/tools.py#L1308). Is this right?

I would go for the version in which either import and export is included. what do you think?

**Comment by nesnoj** [comment]
Result: "Autarky" (already described in NB)

**Comment by nesnoj** [comment]
Autarky is calculated at 4 different places (`flows`, `results_axlxt`, `results_t`, `highlevel`) and I'd like to harmonize them.

I propose to follow the general approach @gplssm has implemented:
- Energy autarky (balance): `autarky = 1 - (E_import / E_demand)` (according to @c-moeller's thesis)
- Temporal autarky (mean): same as in energy, but mean of all time step autarky values

(note that demand is w/o export and battery discharge is implicitly reflected by lower imports)

On the different aggregation levels mentioned above this needs to be adapted.

Nice to have: Temporal autarky (hours): number of hours, where generation>demand (already part of what @nailend implemented)

@gplssm, please go ahead if you like..

**Comment by nesnoj** [comment]
As soon as this is done, single-scenario plots might need refurbishment, e.g. percentage of autark hours.

**Comment by nesnoj** [comment]
Agreed on:
1. Autarky `flows` (mun hourly): Complete balance including batteries, (national and intra-reg.) im- and exports
2. Autarky `results` (mun annual): ratio supply/demand
3. Autarky `highlevel` (ABW annual): ratio supply/demand
