### ISSUE TITLE
El. demand in highlevel results contains export

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#95]
It does make sense to have the export in `results_tables["Stromnachfrage nach Gemeinde"]` but in the highlevel results I propose to remove the export as one cannot distinguish between "real" demand and export from a single total number.
Agree, @gplssm ?

**Comment by nesnoj** [comment]
Also, [`highlevel["Self-consumption annual"]`](https://github.com/windnode/WindNODE_ABW/blob/9b3d7b3ce76b5710aafff9e1aba4404046bd1d20/windnode_abw/analysis/tools.py#L1363) makes use of demand incl. export which is incorrect.

**Comment by gplssm** [comment]
Only change it only in `highlevel_results()`
