### ISSUE TITLE
Results single scenario: further plots

### ISSUE THREAD

**Issue by nesnoj** [windnode/WindNODE_ABW#96]
Post-merge-#27-tasks:

Resolution: ABW
(Data in `results['results_axlxt']`)

**4.1 Balance**

1. Add balance for entire region, either as subplot in the existing mun-graph to the right (also discussed [here](https://github.com/windnode/WindNODE_ABW/pull/79#pullrequestreview-454669214)) or as new bargraph.
2. Table:

|# | Größe | Einheit | Plot/Tabelle | Kommentar | Done? |
|-------|----------|-----------|-----------------|-----------------|-----------------|
| B1 | Full load hours | - | bar | x: technology, y: hours | x |

**5 Emissions**

As we now have more detailed results on emissions #88, please add more plots:

|# | Größe | Einheit | Plot/Tabelle | Kommentar | Done? |
|-------|----------|-----------|-----------------|-----------------|-----------------|
| E1 | Emissions Electricity | t CO2-eq  | stacked bar | x: technology, y: Fix, Var |  |
| E2 | Emissions Heat | t CO2-eq | stacked bar | x: technology, y: Fix, Var |  |
| E3 | Emissions Storages + Transmission | t CO2-eq | stacked bar | x: technology, y: Fix, Var |  |
| E4 | ... | ... | ... | ... |  |

**6 Costs**

|# | Größe | Einheit | Plot/Tabelle | Kommentar | Done? |
|-------|----------|-----------|-----------------|-----------------|-----------------|
| C1 | Generation Electricity (inkl. import) | EUR | stacked bar | x: technology, y: Fix, Var, CO2 certs |  |
| C2 | Generation Heat | EUR | stacked bar | x: technology, y: Fix, Var, CO2 certs |  |
| C3 | Generation Storages + Transmission | EUR | stacked bar | x: technology (Grid, Storages el+th), y: Fix, Var |  |
| C4 | ... | ... | ... | ... |  |

**8 DSM**

|# | Größe | Einheit | Plot/Tabelle | Kommentar | Done? |
|-------|----------|-----------|-----------------|-----------------|-----------------|
| D1 | DSM utilization relative to potential | % |  bar | x: ags, y: DSM utilization. Potential here refers to [flexibilizable demand](https://github.com/windnode/WindNODE_ABW/blob/57529661271779b785fed10570553d32417336bd/windnode_abw/model/region/model.py#L1498-L1502)  |  |

More to come...

**Comment by nailend** [comment]
B1: for the total region or each ags?
if for each ags, as a stacked bar?

**Comment by nesnoj** [comment]
> @nesnoj
> B1: for the total region or each ags?
> if for each ags, as a stacked bar? does it make sense?

For entire region only. I'd go for bars side-by-side..

**Comment by nailend** [comment]
E1 and E2 does already exist in one plot combined, doesnt it?

**Comment by nesnoj** [comment]
> * E1 and E2 does already exist in one plot combined, doesnt it?

Yes it does: one stack per sector but not divided into var+fix.
I added a new plot in 5.2 in #126, there you'll see what I mean. Note that the code for el+th is redundant and might be worth to be put in to draw module.
(also, I tried a sunburst here in 5.3 which I like, it might be worth to be picked up but with low priority. If we continue on this, grid+stor should be added)

> * E3 What do you mean by transmission? the Grid? do you want the emissions of the lines to be stacked?
Yepp, emissions caused by existing and new grid. A grand total for each is sufficient.

Overall goal here is to see what causes most emissions: el, th, grid, stor ?

**Comment by nesnoj** [comment]
Bug in plot 5.1: names for dec pth (e.g. `pth_ASHG_nostor`) are not replaced by readable ones as done in e.g. 5.2

**Comment by nailend** [comment]
> Bug in plot 5.1: names for dec pth (e.g. `pth_ASHG_nostor`) are not replaced by readable ones as done in e.g. 5.2

what do you mean by this? the hoverinfo?

**Comment by nesnoj** [comment]
> what do you mean by this? the hoverinfo?

Yes, and the legend.

**Comment by nailend** [comment]
![grafik](https://user-images.githubusercontent.com/51374526/89638930-f97e4d00-d8ac-11ea-959e-570dd3b63c99.png)

**Comment by nailend** [comment]
which scenario?

**Comment by nesnoj** [comment]
Ok, maybe we're talking about different things. I mean this one:
![em_cap](https://user-images.githubusercontent.com/15910173/89639654-43b3fe00-d8ae-11ea-82a3-e3bfa9fc809d.png)

**Comment by nailend** [comment]
Maybe updateing PRINT_NAMES in tools.py might solve it.

**Comment by nesnoj** [comment]
> Maybe updateing PRINT_NAMES in tools.py with the ones from draw.py solves it.

You gonna do this or shall I?

One more thing:
I'd merge 9 (Energy Exchange) into 3 (Autarky) as it is closely related and give it a new headline such as "Energy Exchange and Autarky" or similar. What do you think?

**Comment by nailend** [comment]
> You gonna do this or shall I?

I will include it in the further plots, feature

> One more thing:
> I'd merge 9 (Energy Exchange) into 3 (Autarky) as it is closely related and give it a new headline such as "Energy Exchange and Autarky" or similar. What do you think?

It will then become a quite big chapter. Maybe moving it up would sufficient?

**Comment by nesnoj** [comment]
> It will then become a quite big chapter. Maybe moving it up would sufficient?

Hmm in the end it belongs together. We would only add 2 plots (I'd remove Mr. Sankey although I love this type) to the 5 existing ones, I don't think that's too large. We could add subsections like I did in no 3 of #64.
Also, we should re-decide on the sections' order.

I've created a new issue for completion of the nb and added these tasks #130.
